name: "emsdk"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mymindstorm/setup-emsdk@v11

      - name: EnvCheckPwd
        run: pwd

      - name: EnvCheckLs
        run: ls -al

      - name: Compile
        run: bash ./compile.sh
