name: "emsdk"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: mymindstorm/setup-emsdk@v11
        version: 3.1.44
        actions-cache-folder: 'emsdk-cache'

      - name: CheckEmccVersion
        run: emcc -v

      - name: Compile
        run: bash ./compile.sh
