name: "emsdk"

on:
  push:
    branches: ["master"]


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.44
          actions-cache-folder: 'emsdk-cache'
      
      - name: Check emcc version
        run: emcc -v

      - name: Download glm
        run: wget -O glm.zip https://github.com/g-truc/glm/releases/download/0.9.9.8/glm-0.9.9.8.zip

      - name: Extract glm
        run: unzip glm.zip

      - name: Compile
        run: bash ./compile.sh

      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'build' # just the build directory is fine

      - name: "Deploy Pages"
        uses: actions/deploy-pages@v2
