name: "emsdk"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v11

      - name: Compile
        run: g++ --version
      - name: Verify
        run: emcc -v
